"""Emit vcstool/vcs2l-compatible `.repos` files, one per layer, with a provenance header."""

from __future__ import annotations

from pathlib import Path
from typing import Dict, Optional, Set

import yaml

from .merge import MergedManifest
from .selectors import resolve_distro_ref

HEADER_PREFIX = "#"


def _repos_body(merged: MergedManifest, layer: str, repo_names_in_order, distro: str) -> str:
    repositories = {}
    for repo_name in repo_names_in_order:
        ref = resolve_distro_ref(merged, repo_name, distro)
        if ref is None:
            continue
        entry = merged.repos[repo_name].entry
        repositories[repo_name] = {"type": entry.type, "url": entry.url, "version": ref}
    if not repositories:
        return ""
    return yaml.dump({"repositories": repositories}, default_flow_style=False, sort_keys=False)


def _header(merged: MergedManifest, layer: str, role: str, distro: str, repo_names) -> str:
    lines = [
        f"{HEADER_PREFIX} Generated by ros-manifest — layer={layer} role={role} distro={distro}",
        f"{HEADER_PREFIX} Provenance (repo: defining manifest):",
    ]
    for repo_name in repo_names:
        lines.append(f"{HEADER_PREFIX}   {repo_name}: {merged.repos[repo_name].source}")
    return "\n".join(lines) + "\n\n"


def emit_layer(
    merged: MergedManifest, layer: str, selected: Set[str], role: str, distro: str
) -> Optional[str]:
    """Return the full `.repos` file text for `layer`, or None if it would be empty."""
    repo_names_in_order = [name for name in merged.layer_repos[layer] if name in selected]
    repo_names_in_order = [
        name for name in repo_names_in_order if resolve_distro_ref(merged, name, distro) is not None
    ]
    if not repo_names_in_order:
        return None
    body = _repos_body(merged, layer, repo_names_in_order, distro)
    header = _header(merged, layer, role, distro, repo_names_in_order)
    return header + body


def emit_manifest(
    merged: MergedManifest, selected: Set[str], role: str, distro: str, out_dir: Path
) -> Dict[str, Path]:
    """Write one `.repos` file per non-empty layer under `out_dir`. Returns layer -> path."""
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    written: Dict[str, Path] = {}
    for layer in merged.layers:
        text = emit_layer(merged, layer, selected, role, distro)
        if text is None:
            continue
        path = out_dir / f"{layer}.repos"
        path.write_text(text)
        written[layer] = path
    return written


def strip_provenance_header(text: str) -> str:
    """Remove the leading `#`-prefixed header block and the blank line after it. Used by tests
    that assert byte-equivalence with hand-authored `.repos` fixtures "modulo the provenance
    header"."""
    lines = text.splitlines(keepends=True)
    idx = 0
    while idx < len(lines) and lines[idx].startswith(HEADER_PREFIX):
        idx += 1
    if idx < len(lines) and lines[idx].strip() == "":
        idx += 1
    return "".join(lines[idx:])
